name: MutalkCI

on:
  pull_request_target:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'resources/**'

jobs:
  mutation_testing:
    runs-on: ubuntu-latest
    permissions:
          pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-stable

      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 15

      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} metacello install "github://pharo-contributions/mutalk/src" BaselineOfMuTalk
        shell: bash
      
      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} mutalk --project=${{github.event.repository.name}}
        shell: bash

      - name: Create report
        id: mutation_report
        shell: bash
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "MUTATION_REPORT<<$EOF"
            sed -e '$a\' "${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_summary.md"
            echo "$EOF"
          } >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.MUTALK_PR }}
          filePath: "${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_summary.md"
      
      - uses: actions/github-script@v6
        env:
          MUTATION_REPORT: steps.mutation_report.outputs.MUTATION_REPORT
        with:
          github-token: ${{ secrets.MUTALK_PR }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MUTATION_REPORT
            })

      - run: cp ${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_summary.md $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: mutation-testing-output
          path: ${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_export.json
