name: MutalkCI

on:
  pull_request_target:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'resources/**'

jobs:
  mutation_testing:
    uses: pharo-contributions/mutalk/.github/workflows/mutalk-workflow.yml@reusable-workflow
