name: MutalkCI

on:
  pull_request_target:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'resources/**'

jobs:
  mutation_testing:
    runs-on: ubuntu-latest
    permissions:
          pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-stable

      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 15

      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} metacello install "github://pharo-contributions/mutalk/src" BaselineOfMuTalk
        shell: bash
      
      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} mutalk --project=${{github.event.repository.name}}
        shell: bash

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: mut_report
          filePath: "${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_summary.md"
      
      - run: cp ${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_summary.md $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: mutation-testing-output
          path: ${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_export.json
